### PR TITLE
Add PTL responsibilities

### LINKED ISSUE #33: Add PTL definition
The TSC has [mostly settled](https://lists.tungsten.io/g/tsc/topic/31036500) on a basic definition for the roles/responsibilities of the PTL role.

This should be captured in the community governance doc.

### PR DESCRIPTION
**Pull request by vmbrasseur**
Closes #33

### CODE REVIEW

**Comment by swill** [comment]
I don't know if I have voting rights, but I am +1.

**Comment by vmbrasseur** [comment]
@swill Right now all community members have voting rights, since we haven't really established that hierarchy for docs yet.

And also: Thank you!

**Comment by Prabhjot-Sethi** [comment]
+1, these updates are very much needed.
not sure if it really needs voting.

i guess someone with the write permission should be able to merge it.

**Comment by swill** [comment]
@vmbrasseur I know this is not the right place to discuss this, but I am curious.  I am not sure what the gating mechanism is for being a "community member".  I am obviously active in the community and am involved in many mailing lists, but I am not sure I am officially a `community member` per say.  If I review the details here, https://tungstenfabric.github.io/website#becoming-a-contributor, my organisation currently does not have a CCLA signed (which I will fix right now).  Should that be the gating factor?

I personally find it difficult to understand what the process is for applying and being recognised as a "community member".  The irony in this is that I have commit access to be able to merge this request, but I still have outstanding questions around the process.  I will take care of the apparent lack of CloudOps not having a signed CCLA today, but I think that illustrates a bit that we are missing some formal process in this area currently.

**Comment by vmbrasseur** [comment]
@swill This is definitely not the place to discuss that. This is a question for the Community Committee, not for a comment on an unrelated issue. ;-)

I recommend first reading through the [Community Governance doc](https://github.com/tungstenfabric/docs/blob/master/Governance/TungstenFabricCommunityGovernance.rst), then adding this to the [agenda for this week's TSC call](https://wiki.tungsten.io/display/TUN/2019-05-09+Meeting+notes), and maybe creating a [doc JIRA ticket](https://jira.tungsten.io/issues/?jql=project%20%3D%20TFB%20AND%20component%20%3D%20Documentation) (select the Documentation component when creating a ticket) if you find we need to get more specific in the community governance doc.

**Comment by swill** [comment]
@vmbrasseur I think you are all set to merge this now.  You have 2x :+1: votes.  I have not been able to find guidelines for the number of votes required to merge in this context (given this is not managed through gerrit, yet).  I know you have the ability to commit, so you should be set to merge now.

The reason I brought it up here is because I am trying to unblock you, but I am also actively trying to understand the contributor process and how the account linking and voting details are supposed to be implemented for contribution in this case.   I will formally raise this at the TSC once I get through trying to piece together the different documents and process details which have been provided.

**Comment by vmbrasseur** [comment]
I get why you're bringing it up, and I do appreciate it and agree that this needs to get sorted out. But an unrelated issue on a repo that almost no one looks at right now isn't a good place to have the conversation. It's a matter for the CC to sort out, not the Docs team.

**Pull request merged**
